/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/access/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Access Session */
        get: operations["get_access_session_api_v1_access_session_get"];
        put?: never;
        /** Upgrade Access Session */
        post: operations["upgrade_access_session_api_v1_access_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_analysis_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_analysis_runs__run_id__get"];
        put?: never;
        post?: never;
        /** Cancel Run */
        delete: operations["cancel_run_api_v1_analysis_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis-runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Events */
        get: operations["run_events_api_v1_analysis_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Media */
        get: operations["source_media_api_v1_sources__source_id__media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessSessionView */
        AccessSessionView: {
            /** Can Analyze */
            can_analyze: boolean;
            /** Retry After Seconds */
            retry_after_seconds?: number | null;
            tier: components["schemas"]["AccessTier"];
        };
        /**
         * AccessTier
         * @enum {string}
         */
        AccessTier: "public" | "judge";
        /**
         * ActionMode
         * @enum {string}
         */
        ActionMode: "reps" | "duration";
        /** AnalysisCandidate */
        AnalysisCandidate: {
            /** Evidence */
            evidence: components["schemas"]["EvidenceSpan"][];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Needs Confirmation */
            needs_confirmation: boolean;
            parameters: components["schemas"]["CandidateParameters"];
            segment: components["schemas"]["Segment"] | null;
            /** Source Id */
            source_id: string;
        };
        /** AnalysisError */
        AnalysisError: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /** AnalysisRunView */
        AnalysisRunView: {
            /** Candidates */
            candidates?: components["schemas"]["AnalysisCandidate"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Empty Reason */
            empty_reason?: "no_evidence" | null;
            error?: components["schemas"]["AnalysisError"] | null;
            /** Id */
            id: string;
            /** Source Id */
            source_id: string;
            stage: components["schemas"]["RunStage"];
            status: components["schemas"]["RunStatus"];
            /** Trigger Seconds */
            trigger_seconds: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** Warnings */
            warnings?: components["schemas"]["AnalysisWarning"][];
        };
        /** AnalysisWarning */
        AnalysisWarning: {
            /**
             * Code
             * @enum {string}
             */
            code: "speech_unavailable" | "visual_unavailable";
            /** Message */
            message: string;
        };
        /** ApiErrorResponse */
        ApiErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** CandidateParameters */
        CandidateParameters: {
            /** Duration Seconds */
            duration_seconds?: number | null;
            mode?: components["schemas"]["ActionMode"] | null;
            /** Reps */
            reps?: number | null;
            /** Rest Seconds */
            rest_seconds?: number | null;
            /** Sets */
            sets?: number | null;
        };
        /** CreateAnalysisRunRequest */
        CreateAnalysisRunRequest: {
            /** Source Id */
            source_id: string;
            /** Trigger Seconds */
            trigger_seconds: number;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "configuration_error" | "provider_error" | "schema_error" | "media_error" | "timeout" | "cancelled";
        /** EvidenceSpan */
        EvidenceSpan: {
            /** End Seconds */
            end_seconds: number;
            /** Start Seconds */
            start_seconds: number;
            type: components["schemas"]["EvidenceType"];
        };
        /**
         * EvidenceType
         * @enum {string}
         */
        EvidenceType: "speech" | "visual";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NotReadyResponse */
        NotReadyResponse: {
            /** Code */
            code: string;
            /**
             * Status
             * @constant
             */
            status: "not_ready";
        };
        /** ReadyResponse */
        ReadyResponse: {
            /**
             * Status
             * @constant
             */
            status: "ready";
        };
        /**
         * RunStage
         * @enum {string}
         */
        RunStage: "queued" | "preparing_media" | "analyzing_evidence" | "expanding_window" | "fusing_candidates" | "completed" | "failed" | "cancelled";
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "completed" | "failed" | "cancelled";
        /** Segment */
        Segment: {
            /** End Seconds */
            end_seconds: number;
            /** Start Seconds */
            start_seconds: number;
        };
        /** SourceSummary */
        SourceSummary: {
            /** Duration Seconds */
            duration_seconds: number;
            /** Id */
            id: string;
            /** Media Url */
            media_url: string;
            /** Origin Url */
            origin_url?: string | null;
            /** Title */
            title: string;
        };
        /** UpgradeAccessSessionRequest */
        UpgradeAccessSessionRequest: {
            /** Access Code */
            access_code: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_access_session_api_v1_access_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessSessionView"];
                };
            };
        };
    };
    upgrade_access_session_api_v1_access_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpgradeAccessSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessSessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_analysis_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAnalysisRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRunView"];
                };
            };
            /** @description 可信代理提供的客户端地址无效。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 请求未通过同源校验。 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 受控视频源不存在。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 分析容量或调用频率已达到限制。 */
            429: {
                headers: {
                    /** @description 再次尝试前需要等待的秒数。 */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 生产分析服务尚未就绪。 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_run_api_v1_analysis_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRunView"];
                };
            };
            /** @description 分析请求不存在、已过期或不属于当前会话。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_analysis_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRunView"];
                };
            };
            /** @description 请求未通过同源校验。 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 分析请求不存在、已过期或不属于当前会话。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_v1_analysis_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 分析请求不存在、已过期或不属于当前会话。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description 生产就绪检查未通过，返回脱敏错误码。 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotReadyResponse"];
                };
            };
        };
    };
    list_sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceSummary"][];
                };
            };
        };
    };
    source_media_api_v1_sources__source_id__media_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
